version: "3.0"
services:
  open-operator-server:
    build:
      context: .
      dockerfile: ./Dockerfile.server
    volumes:
      - .:/usr/src/app
    ports:
      - 8080:8080
    env_file:
      - .env.beta
    networks:
      - local

networks:
  local:
