FROM python:3.10

WORKDIR /usr/src/app

COPY openoperator/ openoperator/
COPY server.py server.py
COPY setup.py setup.py
COPY README.md README.md

RUN python3 -m pip install -e .
RUN pip install python-dotenv

EXPOSE 8080

CMD ["python", "./server.py"]